package ua.lorien.shoppinglist.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ua.lorien.shoppinglist.model.dao.ShoppingList;
import ua.lorien.shoppinglist.model.dao.ShoppingListItem;

import ua.lorien.shoppinglist.model.dao.ShoppingListDao;
import ua.lorien.shoppinglist.model.dao.ShoppingListItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingListDaoConfig;
    private final DaoConfig shoppingListItemDaoConfig;

    private final ShoppingListDao shoppingListDao;
    private final ShoppingListItemDao shoppingListItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingListDaoConfig = daoConfigMap.get(ShoppingListDao.class).clone();
        shoppingListDaoConfig.initIdentityScope(type);

        shoppingListItemDaoConfig = daoConfigMap.get(ShoppingListItemDao.class).clone();
        shoppingListItemDaoConfig.initIdentityScope(type);

        shoppingListDao = new ShoppingListDao(shoppingListDaoConfig, this);
        shoppingListItemDao = new ShoppingListItemDao(shoppingListItemDaoConfig, this);

        registerDao(ShoppingList.class, shoppingListDao);
        registerDao(ShoppingListItem.class, shoppingListItemDao);
    }
    
    public void clear() {
        shoppingListDaoConfig.getIdentityScope().clear();
        shoppingListItemDaoConfig.getIdentityScope().clear();
    }

    public ShoppingListDao getShoppingListDao() {
        return shoppingListDao;
    }

    public ShoppingListItemDao getShoppingListItemDao() {
        return shoppingListItemDao;
    }

}
